CREATE SCHEMA IF NOT EXISTS esm;
USE esm;
CREATE TABLE IF NOT EXISTS tag(
    name CHARACTER VARYING(255) PRIMARY KEY NOT NULL,
    UNIQUE (name));
CREATE TABLE IF NOT EXISTS giftCertificate(
    name CHARACTER VARYING(255) NOT NULL PRIMARY KEY,
    description CHARACTER VARYING(1000) NOT NULL DEFAULT 'empty',
    price MONEY NOT NULL DEFAULT 0.0,
    createDate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdateDate TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration INTEGER NOT NULL DEFAULT 1,
    UNIQUE (name, description));
CREATE TABLE IF NOT EXISTS tag_giftCertificate(
    tag_name CHARACTER VARYING(255),
    giftCertificate_name CHARACTER VARYING(255),
    PRIMARY KEY (tag_name, giftCertificate_name),
    CONSTRAINT FK_tag_name FOREIGN KEY (tag_name) REFERENCES tag (name) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_giftCertificate_name FOREIGN KEY (giftCertificate_name)
    REFERENCES giftCertificate (name) ON DELETE CASCADE ON UPDATE CASCADE);
